version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"
    redisdb:
        container_name: redisdb
        restart: always
        ports:
            - "6379:6379"
    orderdb:
        container_name: orderdb
        restart: always
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Sa123456"
            ACCEPT_EULA: "Y"
    rabbitmq:
        container_name: rabbitmq
        restart: always        
        ports:
            - "5672:5672"
            - "15672:15672"
    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https
        ports:
            - "8000:80"
    basket.api:
        container_name: basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=redisdb:6379"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - redisdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https
        ports:
            - "8001:80"
    ordering.api:
        container_name: orderingapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=Sa123456"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - orderdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https
        ports:
            - "8002:80"
        